### ISSUE TITLE
Reading an entry from a zip file 15 times slower than a very similar Java version

### ISSUE THREAD

**Issue by SteffenIvanhoe** [brendan-duncan/archive#11]
I converted a complex Java program to Dart. Part of the program is to go throug various zip archives and read one entry of multiple existing ones in each zip file. Replacing the Java ZipFile/ZipEntry with your Archive/ArchiveFile was easy. The problem arrived when running the program. Unit tests went through but the Dart program took about 30 seconds compared to 2 seconds for the Java version.

I know from other measures I have done that Dart is on average 20-40% slower than Java for equivalent algorithms, for some library functions I found Dart equivalents up to 100% slower than their Java counterparts.

The performance of your archive packages points to something more serious. Probably you use very inefficient algorithms? Or could it be that you decode all zip entries of an archive file no matter whether they get used? In my example I always use only one entry and I would expect that the content gets decompressed only when referenced and not before to save time and memory.

Could you have a look at this issue?

**Comment by brendan-duncan** [comment]
The zip entry will only be decompressed when it's accessed.
I'm sure there are places where the decompression can be optimized. I suspect (as a guess) Java's Zip library uses a native decompression rather than one written in Java. I will try and find some time to look at this, but things have been very busy lately so I apologize if I can't get to it for a bit.

**Comment by brendan-duncan** [comment]
I found the problem. CrC verification was set to true by default, which requires decompression and therefore is slow.  I pushed an update to have CrC verification disabled by default. You can also manually disable it: zipDecoder.decodeBytes(bytes, verify: false);

**Comment by SteffenIvanhoe** [comment]
Thank you for the effort!

Tested it again and the performance difference got a lot smaller from 15 
times slower to 3 times slower. Still a lot but this might be caused by 
a very efficient native Java implementiation. But I have not checked that.

Steffen

Am 24.02.2015 um 05:56 schrieb Brendan Duncan:
