### ISSUE TITLE
Null safe `package:archive`

### ISSUE THREAD

**Issue by davidmorgan** [brendan-duncan/archive#113]
Hi,

You may have heard that Dart is getting a null safe type system:

https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3

It's not yet generally available, but we have already started migrating widely used packages to null safety, see for example [package:path](https://github.com/dart-lang/path/pull/89/files), so that they are available with null safety as the feature launches.

Because `package:archive` is widely used we'd like to migrate it sooner rather than later. Would you be open to accepting PRs doing the migration, please?

Thanks! Of course, I'm happy to answer any questions you have.

**Comment by brendan-duncan** [comment]
Hi David, sorry for the delay. Yes, I'd be happy to accept PRs for this. I'm very happy Dart is getting null safety features, it's caused several errors in the past and one feature I miss from Swift.

**Comment by davidmorgan** [comment]
Sounds good, thanks!
