### ISSUE TITLE
Could not find End of Central Directory Record

### ISSUE THREAD

**Issue by titiv5** [brendan-duncan/archive#115]
FormatException: Could not find End of Central Directory Record

------- STACK TRACE -------
#0      ZipDirectory._findSignature (package:archive/src/zip/zip_directory.dart:149)
#1      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:28)
#2      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:20)
#3      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14)
#4      FileUtil.unZip (package:flutter_sccba_utils/file_util.dart:109)
#5      _SplashPageState._downloadResource (package:sccba_bank_app/page/splash_page.dart:158)
#6      _SplashPageState.asyncInitState (package:sccba_bank_app/page/splash_page.dart:180)

Here is my code：

 ```
 static unZip(String zipPath, String unZipDir) {
    final bytes = File(zipPath).readAsBytesSync();
    final archive = ZipDecoder().decodeBytes(bytes);
    // Extract the contents of the Zip archive to disk.
    for (final file in archive) {
      final filename = file.name;
      if (file.isFile) {
        final data = file.content as List<int>;
        File('$unZipDir${Platform.pathSeparator}' + filename)
          ..createSync(recursive: true)
          ..writeAsBytesSync(data);
      } else {
        Directory('$unZipDir${Platform.pathSeparator}' + filename)
          ..create(recursive: true);
      }
    }
  }
```

I found that the app unzipped normally in Debug mode and unzipped the above error in Release mode

**Comment by wuhengzhi** [comment]
The format is not identical. e.g. unzip tar with TarDecoder instead of ZipDecoder.

**Comment by Herinn** [comment]
I don't know if you found a solution, but I had the same error, and I knew my file was a Zip and not a Tar. I solved it by importing :
```
import 'package:archive/archive.dart';
import 'package:archive/archive_io.dart';
```
instead of one or the other.
