### ISSUE TITLE
解压的时候，内存溢出

### ISSUE THREAD

**Issue by changleibox** [brendan-duncan/archive#119]
你好，在解压zip文件的时候，内存溢出了，设备是ipad，系统是14.0.1，文件解压前大小为2.9M，麻烦帮我解决下，谢谢了

**Comment by robert-ancell** [comment]
According to Google Translate: "Hello, when decompressing the zip file, the memory overflowed, the device is ipad, the system is 14.0.1, the size of the file before decompression is 2.9M, please help me solve it, thank you ". Title is "When decompressing, the memory overflowed "
