### ISSUE TITLE
Publish null-safe version

### ISSUE THREAD

**Issue by sestegra** [brendan-duncan/archive#129]
Could you publish a prerelease of this package please?
See related [documentation](https://dart.dev/null-safety/migration-guide#step5-publish).

**Comment by jagmit** [comment]
+1
Also there has been a lot for (breaking) changes since the release of version 2.0.13 (7efdfea6e8eeec4b09036b60f3f927ebc020af0b) so it would make sense to (also) make a regular release.

@brendan-duncan I'm happy to help if there is any additional work required to have a releasable version!

**Comment by brendan-duncan** [comment]
Kevin Moore published 3.0.0-nullsafety.0 last week. Is there something else that needs to be published?

**Comment by sestegra** [comment]
Thank you for the update
