### ISSUE TITLE
How to set compression level in ZipFileEncoder?

### ISSUE THREAD

**Issue by aiurovet** [brendan-duncan/archive#135]

**Comment by brendan-duncan** [comment]
You should be able to set it from from the following methods. The level argument in these functions should set the deflate compression level, [0-9].
```
ZipFileEncoder {
    void zipDirectory(Directory dir, {String? filename, int? level}) // short-hand for: create, addDirectory, close

    void create(String zip_path, {int? level})
}
```

This class has an admittedly not great API.

**Comment by aiurovet** [comment]
Thank you, Brendan.

Was that added in v3.0.0 of the package? I've got the latest stable v2.0.13, where neither create(), nor zipDirectory() has such parameter. Essentially, that's why I've asked the original question.

**Comment by brendan-duncan** [comment]
Oh, you're right, it had slipped in in-between 2.0.13 and when Kevin added the 3.0 nullability changes. That's too bad. I suppose there's a couple options: 1) easiest for me, you could pull the commit from git and use that in your project until you can update to 3.0, https://github.com/brendan-duncan/archive/commit/05443cfdc1bdcdcef75412d55bce8945180a5f54. 2) easiest for you, I could try and figure out how to back-port the changes to a 2.0.14. I suppose it would be good for me to figure how to do back-ports with pub.

**Comment by aiurovet** [comment]
Thanks a lot, Brendan, for your prompt response.

Originally, I tried to upgrade the package to v3.0.0, but it required me to upgrade Dart SDK to unstable v2.12, so I hesitated and asked for help. Given the missing compression level is a genuine issue, I decided to try that option. I feel uncomfortable to take too much of your time on a non-pressing issue.

All good: I've upgraded without any problem, everything works as on the stable channel, so the ticket can be closed. You can leave it though if you prefer to undertake further action from your side.
