### ISSUE TITLE
Zip and Tar archives are not cross-platform

### ISSUE THREAD

**Issue by aiurovet** [brendan-duncan/archive#136]
Hi team,

It seems to me I've found a serious bug. I checked that if I zip a directory with subdirectories on Windows using the package, then unzip it using the package under Linux, it extracts all files with the filenames like 'subdir\filename.ext' (literally, with the single quotes in order to avoid misinterpretation of the backslash as a control character). All files lie flat: in the same directory, no structure preserved. And even using standard GUI tools like Engrampa will show the same content.

Then I checked TAR creation and found the same issue.

I found that according to ZIP standard, all path must be stored using forward slashes as directory separators. Here is an example of the doco I found at https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

4.4.17 file name: (Variable)

       4.4.17.1 The name of the file, with optional relative path.
       The path stored MUST NOT contain a drive or
       device letter, or a leading slash.  All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility with Amiga
       and UNIX file systems etc.  If input came from standard
       input, there is no file name field.  

       4.4.17.2 If using the Central Directory Encryption Feature and 
       general purpose bit flag 13 is set indicating masking, the file 
       name stored in the Local Header will not be the actual file name.  
       A masking value consisting of a unique hexadecimal value will 
       be stored.  This value will be sequentially incremented for each 
       file in the archive. See the section on the Strong Encryption 
       Specification for details on retrieving the encrypted file name. 
       Refer to the section in this document entitled "Incorporating PKWARE 
       Proprietary Technology into Your Product" for more information.

I'm pretty sure the same applies to TAR format.

This is happening in v3.0.0, but I haven't checked any other.

**Comment by brendan-duncan** [comment]
Thanks for catching this. I pushed a git update to force / paths, but I still need to check it on Linux.

**Comment by brendan-duncan** [comment]
My quick test seemed to be ok. Zipping a directory on windows, used the unzip program on Linux extracted it fine. If you can verify the git version works for you I'll push the fix.

**Comment by aiurovet** [comment]
Terrific! Worked as expected. Thank you very much.

**Comment by aiurovet** [comment]
I thought that more precisely would be to replace Path.separator with '/' rather than explicit Windows '\\'. In that case however, if someone creates a file with '\' on Unix-like system, it will get through, but might get wrongly extracted on Windows. I've got an evidence that some extractors on Windows are recognising backslashes as directory separators. A really weird situation. Overall, I tend to agree with your version.

**Comment by brendan-duncan** [comment]
Great, I'll publish the updated version shortly

**Comment by aiurovet** [comment]
👍
