### ISSUE TITLE
Data calculation abnormal

### ISSUE THREAD

**Issue by godgege** [brendan-duncan/archive#144]
![image](https://user-images.githubusercontent.com/13862699/117543111-02739900-b04e-11eb-929d-bea3e959081d.png)

Happened in the second sheet, it feels like it's messy

**Comment by brendan-duncan** [comment]
I'm sorry, I don't know what this issue is about. Is this about compressed archives?

**Comment by ismanong** [comment]
[test.xlsx](https://github.com/brendan-duncan/archive/files/6448125/test.xlsx)

After you download the file, check to see if there is a problem with the rendered content. Thank you

**Comment by brendan-duncan** [comment]
I don't know what an xlsx file is. I'm going to close this issue. If there is problem with decompressing zip or other compressed files, please make the issue about that.

**Comment by ismanong** [comment]
Thank you for your reply, I will study and study
