### ISSUE TITLE
Add `followLinks` option in `zipDirectory` and `addDirectory`

### ISSUE THREAD

**Issue by narumishi** [brendan-duncan/archive#146]
In some cases, symbolic links are not desired. Please add this param and just pass it to 
https://github.com/brendan-duncan/archive/blob/9de7a0544457c6aba755ccb65abb41b0dc1db70d/lib/src/io/zip_file_encoder.dart#L35-L36

Zip/tar.. encoders should add this param.

**Comment by brendan-duncan** [comment]
That seems like a good thing to add. Not sure when I'll be able to get to it.

**Comment by narumishi** [comment]
I believe it should be an easy and quick fix to add `followLinks ` in `TarFileEncoder.tarDirectory`, `TarFileEncoder.addDirectory`, `ZipFileEncoder.zipDirectory` and `ZipFileEncoder.addDirectory`.

If it's okay, I would like to open a pull request.

**Comment by brendan-duncan** [comment]
That would be great, thank you
