### ISSUE TITLE
How I can add this lib to my Dart app as a dependency? 

### ISSUE THREAD

**Issue by fellahi-ali** [brendan-duncan/archive#149]
Hi, I'm new to **Dart**, and I want to play around with this lib, 
but I don't know how to add it to my **Dart** project, can anyone help me please?
And I think its also good to have this info on the README file.
Many thanks.

**Comment by brendan-duncan** [comment]
Dart uses a package system called pub. Documenting how to use pub would be beyond the scope of the README file, there are a number of Dart tutorials and documentation. Here's the Dart documentation on packages, https://dart.dev/guides/packages.

Basically, you'll want to edit the file pubspec.yaml in the root folder of your project. Add a 'dependencies' section if it's not already there, and add something like:
  archive: '>=3.1.0 <4.0.0'

You can look at the pubspec.yaml in this library as an example,
https://github.com/brendan-duncan/archive/blob/master/pubspec.yaml
