### ISSUE TITLE
TAR decoder shows unexpected output

### ISSUE THREAD

**Issue by S-Man42** [brendan-duncan/archive#156]
I have this TAR ball (https://s-man42.de/bg.tar  -> attaching tarballs is not allowed in GitHub unfortunately). I know, it contains 1 file named `lat.mp3`

However, I tried to open it with your plugin:

```
   try {
      var archive= TarDecoder().decodeBytes(file.bytes);

      print('EXTRACTED TAR');
      print(archive.length);

      for (final packedfile in archive) {
        final filename = packedfile.name;
        if (packedfile.isFile) {

          final data = packedfile.content as List<int>;
          print(packedfile.name);
        }
      }

    }catch(e){print('TRIED TAR');}
```

That returns:

```
I/flutter ( 5487): EXTRACTED TAR
I/flutter ( 5487): 4
I/flutter ( 5487): ÿØÿà
I/flutter ( 5487):
I/flutter ( 5487): YêîWóâ?*¤ªóÔ`´®Ó¶Op|S½¦bÖè<>**EÎÓ@æ~å:Ra
I/flutter ( 5487): ã¼Ý(@ÊÈe6ØçþñÓáù©ÎÆiÝÜþhø~òáKhsÌCGÒ?ùBÉ²Þ 4_s5Æ»ù³'÷¡ù~ò0Yé¤%'6½á±º Þn¨×

```

So, I guess, I am doing something wrong: 
1. It show content of 4 files, instead of 1
2. None of the printed file names is the correct one.

Please, could you tell me, what I missed?

**Comment by brendan-duncan** [comment]
Sorry for the delay. I'm not sure what to make of this tar file. Looking at it with a hex editor, it doesn't seem to be a regular tar at all.

7-zip decodes it and shows it has a single lat.mp3 file in it, reportedly 31,875 bytes, which is bigger than the tar file, so there must be a compression layer on top of the tar.

But looking at it with a hex editor, there seems to be what looks to me like a photoshop PSD file at the start of it. 

Very strange, and I have no idea what kind of file it is, but it's not a TAR as far as I can tell.
