### ISSUE TITLE
archive 3.1.3 & 3.1.4 no longer compile for web

### ISSUE THREAD

**Issue by mtallenca** [brendan-duncan/archive#165]
lib/src/util/crc64.dart was added in version 3.1.3. There are numerous int values that cannot be represented in javascript.  Web compilation with 3.1.3 or 3.1.4 fails with many of the following...

../flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.1.4/lib/src/util/crc64.dart:277:3:
Error: The integer literal 0xe0ada17364673f59 can't be represented exactly in JavaScript.
  0xe0ada17364673f59
  ^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.1.4/lib/src/util/crc64.dart:6:21:
Error: The integer literal 0x7fffffffffffffff can't be represented exactly in JavaScript.
    return (value & 0x7fffffffffffffff) >> 8 | 0x0080000000000000;
                              ^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.1.4/lib/src/util/crc64.dart:13:10:
Error: The integer literal 0xffffffffffffffff can't be represented exactly in JavaScript.
  crc ^= 0xffffffffffffffff;
              ^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/archive-3.1.4/lib/src/util/crc64.dart:17:16:
Error: The integer literal 0xffffffffffffffff can't be represented exactly in JavaScript.
  return crc ^ 0xffffffffffffffff;
                       ^^^^^^^^^^^^

**Comment by brendan-duncan** [comment]
Hi, I just realized this. Fix is coming shortly.

**Comment by brendan-duncan** [comment]
Fixed in archive 3.1.5
