### ISSUE TITLE
Tar with long file path produce FormatException: EOF reached without finding string terminator

### ISSUE THREAD

**Issue by Vincent-Ma** [brendan-duncan/archive#166]
Hello,

There is a bug when reading some tar archive with files that have long path.
It raises a `FormatException: EOF reached without finding string terminator`

I believe inside a tar when the file path is too long it is placed into a file named *././@LongLink*.
Currently the code expects this long path to be null terminated (by using `InputStream.readString()`).
But on some tar archive it seems there is no null byte and the long path simply equal the whole content of the *././@LongLink* file.
In this case `readString()` produce an exception.

Here are example of tar gz files where the issue occur:
- https://pub.dev/packages/firebase_messaging/versions/10.0.8.tar.gz
- https://pub.dev/packages/win32/versions/2.2.9.tar.gz
- https://pub.dev/packages/webview_flutter/versions/2.1.1.tar.gz

This issue does not happen in the test case (`test/tar_test.dart` "long file name") because the file *././@LongLink* in the tar (`res/tar/x.tar`) does have the extra null bytes.

A very simple quick fix could be to just add the `size` argument in `readString()` (`lib/src/tar_decoder.dart:34`) like so:
`tf.rawContent!.readString(size: tf.fileSize);`
This would always read the whole size of the file *././@LongLink* instead of looking for a null byte.

Or may be, a better solution could be to create a new method that take into account when the null byte is present and when it is not

### Steps to Reproduce

1. Download the tar gz archive:
`wget https://pub.dev/packages/firebase_messaging/versions/10.0.8.tar.gz -O longName.tar.gz`

2. Run the code:
```
import 'dart:io';
import 'package:archive/archive.dart';

void main(List<String> args) {
  final tarballBytes = File('longName.tar.gz').readAsBytesSync();
  final tarBytes = GZipDecoder().decodeBytes(tarballBytes);
  TarDecoder().decodeBytes(tarBytes);
}
```
#### Expected results:

Success.

#### Actual results:
```
FormatException: EOF reached without finding string terminator
#0      InputStream.readString (package:archive/src/util/input_stream.dart:195:7)
#1      TarDecoder.decodeBuffer (package:archive/src/tar_decoder.dart:39:34)
#2      TarDecoder.decodeBytes (package:archive/src/tar_decoder.dart:12:12)
```

**Comment by mx1up** [comment]
experiencing the same problem, created PR
