### ISSUE TITLE
ZipDecoder().decodeBytes( failes with Dart.jar v213.5744.122 from IDEA 2012.3

### ISSUE THREAD

**Issue by VladimirSrednikh** [brendan-duncan/archive#177]
Meanwhile, 7Zip and java.exe successfully work with this archive.

this lead to fail when call 
flutter doctor -v
with installed IDEA

**Comment by brendan-duncan** [comment]
I'll look into it.

**Comment by brendan-duncan** [comment]
I fixed the exception that caused the error for that archive, tested decoding the archive locally. I pushed what should be the fix to archive 3.1.8. But I'm not sure how to update Flutter packages used by `flutter doctor` to pick up the fixed version.
