### ISSUE TITLE
BZip2Decoder decode methods takes very long time to return value

### ISSUE THREAD

**Issue by yahu1031** [brendan-duncan/archive#187]
I have 83MB(93MB on disk) file with `.tar.bz2` extension. And Using `BZip2Decoder().decodeBuffer(input, output: output)` this takes forever to get `List<int>` value. Any other way to extract this file in an asynchronous way? This process blocks my UI.

NOTE: Using the git branch

**Comment by yahu1031** [comment]
```dart
InputFileStream input = InputFileStream(downloadedFile.path);
// remove the .bz2 extension
// String outputFile = fileName.substring(0, fileName.length - 4);
OutputFileStream output = OutputFileStream(path.join(
    extractionPath, 'temp', fileName.substring(0, fileName.length - 4)));
List<int> wtf = BZip2Decoder().decodeBuffer(input, output: output);
input.close();
output.close();
print(wtf.length);
InputFileStream archiveInput = InputFileStream(path.join(
    extractionPath,
    'temp',
    downloadedFile.path
        .split('/')
        .last
        .split('.')
        .removeLast()
        .splitMapJoin('.')));
Archive archive = TarDecoder().decodeBuffer(input);
```
This sample code block I use and it takes a pretty long time to hit `input.close()`. Sometimes it never hits and also it blocks the whole UI.

**Comment by yahu1031** [comment]
Yes, I tried a similar process. but it literally takes more than 5 mins. but still doesn't do.
```dart
await console.log(LogTypeTag.info, 'Started Extracting to $tarFile');
InputFileStream input = InputFileStream(downloadedFile.path);
OutputFileStream output = OutputFileStream(tarFile);
BZip2Decoder().decodeBuffer(input, output: output);
await console.log(LogTypeTag.info, 'Ended Extracting to $tarFile');
```
in console
```
[log] INFORMATION [ Wed, 2/16/2022 1:55:52 AM ] - Started Extracting to C:\Users\yaswa\AppData\Roaming\flinma\flinma\Git-2.35.1.2-64-bit.tar
```
When I'm logging this is 02:02 AM, still didn't complete it.

**Comment by brendan-duncan** [comment]
I'll have to test decoding a large file, see if there's anything that can be done about it. OutputFileStream may be responsible for the slowness, at least a significant portion of the time. It's doing a *lot* of fie writing, but file IO is very slow. OutputFileStream really needs to do some buffering to reduce the total number of file writes.

**Comment by yahu1031** [comment]
Take [this file](https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.2/Git-2.35.1.2-32-bit.tar.bz2) as example.

**Comment by brendan-duncan** [comment]
I pushed the updates to git. The default OutputFileStream buffer cache is 8k. I found upping even to 64k didn't affect the decoding time very much, so with the 8k buffer it seems to be CPU bound with the actual decoding, rather than IO bound as it was previously. On my computer it's taking 24 seconds to decode the bz2 to the output file.

There's a couple other things I wanted to look into cleaning up before I push the new version.

**Comment by yahu1031** [comment]
Did you try that on windows? Cause windows sometimes do fast comparing to mac. But Mac doesn't. It takes years. And also don't know if it was failed or not too.

**Comment by brendan-duncan** [comment]
I tested the buffered write on an an M1 MacBook.

**Comment by brendan-duncan** [comment]
Are you saying the git version is still slow?

**Comment by yahu1031** [comment]
lemme recheck it.

**Comment by yahu1031** [comment]
Cool, this is faster than before.
```dart
InputFileStream input = InputFileStream(downloadedFile.path);
OutputFileStream output = OutputFileStream(tarFile);
BZip2Decoder().decodeBuffer(input, output: output);
input.close();
output.close();
InputFileStream tarInput = InputFileStream(tarFile);
Archive archive = TarDecoder().decodeBuffer(tarInput);
tarInput.close();
for (ArchiveFile file in archive.files) {
  String filePath = path.join(extractionPath, file.name);

  if (!file.isFile || !isWithinOutputPath(extractionPath, filePath)) {
    continue;
  }
  File output = File(filePath);
  await output.create(recursive: true).then((File f) async {
    await f.open(mode: FileMode.write).then((RandomAccessFile fp) async {
      List<int> bytes = file.content as List<int>;
      await fp.writeFrom(bytes).then((RandomAccessFile fp) async {
        file.clear();
        await fp.close();
      });
    });
  });
}
archive.clear();
```
This is how I used it.

Things also found is, Closing file streams may also affect it to be fast.

Thanks for the quick fix 😃
