### ISSUE TITLE
Cannot delete created Tar file

### ISSUE THREAD

**Issue by Migarl** [brendan-duncan/archive#202]
Hey there!

I am struggling to delete a created Tar file on Windows.

```
final encoder = TarFileEncoder();
encoder.tarDirectory(
  dir,
  compression: 1,
);
final tgzFile = File("${dir.path}.tar.gz");
tgzFile.deleteSync();
```

The above code results in 
```
FileSystemException: Cannot delete file, path = 'C:\Users\migarl\AppData\Local\Temp\tempdir.tar.gz' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
```

Is this a bug or did I something wrong?

Thanks for your help and your nice work!

**Comment by brendan-duncan** [comment]
Just a guess, maybe the Dart garbage collection hasn't closed that particular File object yet from the tarDirectory function. Also, file IO in general is cached by the OS, and a common source of problems is trying to read a file immediately after you write to it. So I would try and defer the deleteSync somehow.

**Comment by Migarl** [comment]
Thanks for the quick response and the advise!
Good to know. I'll try it, thanks!
