### ISSUE TITLE
'Invalid CRC for file in archive.'  Does this package support aes encrypted zip?

### ISSUE THREAD

**Issue by 7AveNooN7** [brendan-duncan/archive#204]
```dart
var zipAsBytes = File('${appDocDir.path}/test.zip').readAsBytesSync();
final archive = ZipDecoder().decodeBytes(zipAsBytes, verify: true, password: '123');
```

When Zip is created by 7zip with aes encryption: 
1) It gives the Unhandled Exception: FormatException: Invalid CRC for file in archive. 
2) Without verify set to 'true' it goes with Unhandled Exception: FormatException: Missing extension byte (at offset 5)

When zip is created by 7zip with ZipCrypto it works perfectly, but ZipCrypto is useless.

Does this package support decoding aes encrypted zip?

**Comment by brendan-duncan** [comment]
Encryption is only minimally implemented currently, no AES support. Happy to take PRs to implement it, I don't think I'll have time to do it.

**Comment by 7AveNooN7** [comment]
Ok, understood!
