### ISSUE TITLE
Building Flutter DevTools failing after `archive 3.3.3` release

### ISSUE THREAD

**Issue by elliette** [brendan-duncan/archive#221]
Flutter DevTools (https://github.com/flutter/devtools) depends on `package:image` which depends of `package:archive`. 

Compiling Flutter Devtools to JS is failing with the following error:

```
../../../../../.pub-cache/hosted/pub.dev/archive-3.3.3/lib/src/util/aes_decrypt.dart:1:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
```

`dart:ffi`  is not available on the web, which is why the JS compilation is failing. It looks like this is the commit that pulled in that new dependency: https://github.com/brendan-duncan/archive/commit/3dd6a0534cbc26c20ab0e6e541c87772836a2c06

See: https://github.com/flutter/devtools/actions/runs/3447346680/jobs/5753452668

**Comment by brendan-duncan** [comment]
Sorry about that, last minute change caused the error. I published 3.3.4.

**Comment by elliette** [comment]
Thank you!

**Comment by kevmoo** [comment]
Can this be closed?
