### ISSUE TITLE
archive class to save as file(xlsx) did not work

### ISSUE THREAD

**Issue by YancyHsu** [brendan-duncan/archive#247]
no error display, but when open the Excel file, it shows "File Corrupted"

not worked code:

    final outputStream = OutputFileStream(xlsxFilePath);
    var outputBytes = ZipEncoder().encode(_archive)!;
    outputStream.writeBytes(outputBytes);

**Comment by YancyHsu** [comment]
but when i extract Archive to a folder first, then zip it, it works, the Excel file is OK. So i think something wrong with OutputFileStream, maybe i misuse it? Can somebody help?

worked code:
    var outputFolder = 'output';
    extractArchiveToDisk(_archive, outputFolder);
    var dir = Directory(outputFolder);
    var encoder = ZipFileEncoder();
    encoder.zipDirectory(dir, filename: xlsxFilePath);
    dir.deleteSync(recursive: true);

**Comment by Tristl** [comment]
Got similar problem
Try with version 3.3.2, until that version it works for me
