### ISSUE TITLE
192-bit AES encryption is misdetected as 256-bit

### ISSUE THREAD

**Issue by alexhenrie** [brendan-duncan/archive#262]
[zip_file.dart](https://github.com/brendan-duncan/archive/blob/6fc3b89fcdb89b593402e0dabc13a7d7fd3f762d/lib/src/zip/zip_file.dart#L202) currently contains the following:

```dart
    if (_aesHeader!.encryptionStrength == 1) {
      // 128-bit
      salt = input.readBytes(8).toUint8List();
      keySize = 16;
    } else if (_aesHeader!.encryptionStrength == 1) {
      // 192-bit
      salt = input.readBytes(12).toUint8List();
      keySize = 24;
    } else {
      // 256-bit
      salt = input.readBytes(16).toUint8List();
      keySize = 32;
    }
```

Look at how the `if` and the `else if` have the same condition: That means that the `else if` can never be true, so 192-bit encryption gets processed as 256-bit encryption.

**Comment by brendan-duncan** [comment]
Yup. Looks like someone got lazy with copy/paste. I'll get that fixed up shortly.

**Comment by brendan-duncan** [comment]
It's fixed in Git now. I'll try to get to pushing a release with the fix when I get another free moment.

**Comment by alexhenrie** [comment]
Thank you!
