### ISSUE TITLE
InputFileStream not close in extractFileToDisk

### ISSUE THREAD

**Issue by czw299** [brendan-duncan/archive#263]
When I use **extractFileToDisk** on Windows, the zip file could not be delete until exit the app.
![image](https://github.com/brendan-duncan/archive/assets/48857658/c4b60c7e-9afb-44bc-beaa-5eb1df1e46f9)
It seem that a **InputFileStream** was fogot to close:
![image](https://github.com/brendan-duncan/archive/assets/48857658/39e43c08-4080-4553-b6f5-37f3261c88c5)
Could you fix it? Thanks. Sorry for my bad English.

**Comment by ElHaban3ro** [comment]
I also have this same problem and I can't find how to fix it :( Were you able to fix it?

**Comment by czw299** [comment]
> I also have this same problem and I can't find how to fix it :( Were you able to fix it?

I just wrote my own imitation of the original function, and close all InputFileStream, and it worked fine. But this is a simplified version that removes some of the original features, such as password support, which is enough for me.
![image](https://github.com/brendan-duncan/archive/assets/48857658/dc198554-aedc-43ff-8c02-4768bc368a14)

**Comment by czw299** [comment]
> I also have this same problem and I can't find how to fix it :( Were you able to fix it?

I just wrote my own imitation of the original function, and close all InputFileStream, and it worked fine. But this is a simplified version that removes some of the original features, such as password support, which is enough for me.

`
Future<void> extractFileToDisk2(String inputPath, String outputPath) async {
  var archivePath = inputPath;
  final input = InputFileStream(archivePath);
  Archive archive = ZipDecoder().decodeBuffer(input);

  for (final file in archive.files) {
    final filePath = p.join(outputPath, p.normalize(file.name));

    if (!isWithinOutputPath(outputPath, filePath)) {
      continue;
    }

    if (!file.isFile && !file.isSymbolicLink) {
      Directory(filePath).createSync(recursive: true);
      continue;
    }

    if (file.isSymbolicLink) {
      final link = Link(filePath);
      await link.create(p.normalize(file.nameOfLinkedFile), recursive: true);
    } else {
      final output = File(filePath);
      final f = await output.create(recursive: true);
      final fp = await f.open(mode: FileMode.write);
      final bytes = file.content as List<int>;
      await fp.writeFrom(bytes);
      file.clear();
      await fp.close();
    }
  }

  await archive.clear();
  await input.close();
}
`

**Comment by czw299** [comment]
I just wrote my own imitation of the original function, and turned off all inputFileStream, and it worked fine. But this is a simplified version that removes some of the original features, such as password support, which is enough for me.

`Future<void> extractFileToDisk2(String inputPath, String outputPath) async {
  var archivePath = inputPath;
  final input = InputFileStream(archivePath);
  Archive archive = ZipDecoder().decodeBuffer(input);

  for (final file in archive.files) {
    final filePath = p.join(outputPath, p.normalize(file.name));

    if (!isWithinOutputPath(outputPath, filePath)) {
      continue;
    }

    if (!file.isFile && !file.isSymbolicLink) {
      Directory(filePath).createSync(recursive: true);
      continue;
    }

    if (file.isSymbolicLink) {
      final link = Link(filePath);
      await link.create(p.normalize(file.nameOfLinkedFile), recursive: true);
    } else {
      final output = File(filePath);
      final f = await output.create(recursive: true);
      final fp = await f.open(mode: FileMode.write);
      final bytes = file.content as List<int>;
      await fp.writeFrom(bytes);
      file.clear();
      await fp.close();
    }
  }

  await archive.clear();
  await input.close();
}`

**Comment by czw299** [comment]
> I also have this same problem and I can't find how to fix it :( Were you able to fix it?

I just wrote my own imitation of the original function, and turned off all inputFileStream, and it worked fine. But this is a simplified version that removes some of the original features, such as password support, which is enough for me.
```
Future<void> extractFileToDisk2(String inputPath, String outputPath) async {
  var archivePath = inputPath;
  final input = InputFileStream(archivePath);
  Archive archive = ZipDecoder().decodeBuffer(input);

  for (final file in archive.files) {
    final filePath = p.join(outputPath, p.normalize(file.name));

    if (!isWithinOutputPath(outputPath, filePath)) {
      continue;
    }

    if (!file.isFile && !file.isSymbolicLink) {
      Directory(filePath).createSync(recursive: true);
      continue;
    }

    if (file.isSymbolicLink) {
      final link = Link(filePath);
      await link.create(p.normalize(file.nameOfLinkedFile), recursive: true);
    } else {
      final output = File(filePath);
      final f = await output.create(recursive: true);
      final fp = await f.open(mode: FileMode.write);
      final bytes = file.content as List<int>;
      await fp.writeFrom(bytes);
      file.clear();
      await fp.close();
    }
  }

  await archive.clear();
  await input.close();
}
```

**Comment by brendan-duncan** [comment]
Sorry for the long delay, life has been very busy lately. I pushed an update to this on git. I have some other things in this library I've been neglecting lately I wanted to try to get to before pushing a version update.

**Comment by czw299** [comment]
> Sorry for the long delay, life has been very busy lately. I pushed an update to this on git. I have some other things in this library I've been neglecting lately I wanted to try to get to before pushing a version update.

😄It doesn't matter. Thanks a lot. Have a nice day.
