### ISSUE TITLE
Archive is vulnerable to symlink path traversal

### ISSUE THREAD

**Issue by BlueSquare1** [brendan-duncan/archive#265]
Hello, 

while doing some security testing on `archive` package, we noticed that it supports symlinks, while symlinks might be an intended functionality of your package, we do believe that symlinks pointing outside the extraction directory are more of a security risk than a feature, below is an example where we created a symlink pointing to a file `secret.txt` in the parent directory, zipped it and extracted it using `extractFileToDisk` method from `archive` package, the symlink was created back after extraction.

![Screenshot from my workstation](https://github.com/brendan-duncan/archive/assets/129080649/0e2b01f7-1477-4037-9669-ae8eb3ba0ae6)
*Screenshot from my workstation*

![Screenshot from my mobile device](https://github.com/brendan-duncan/archive/assets/129080649/b8298ced-ac3f-4838-90fa-3822363c3510)
*Screenshot from my test mobile device*

**Comment by brendan-duncan** [comment]
I updated extractArchiveToDisk and extractFileToDisk to not create symlinks that begin with '..' or '/', which would be outside of the extracted path.

**Comment by jonasfj** [comment]
@brendan-duncan you could consider referencing the CVE in your changelog:
https://github.com/advisories/GHSA-9v85-q87q-g4vg
