### ISSUE TITLE
Package flagged as vulnerable

### ISSUE THREAD

**Issue by dditim** [brendan-duncan/archive#276]
Hello,

we use Lottie in our app, while Lottie is using archive as a transitive dependency.
However, since today, our Pipeline fails its vulnerability check due to the archive package. 
https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-9v85-q87q-g4vg/GHSA-9v85-q87q-g4vg.json

Is this a known issue and will be fixed in the near future?

Thank you!

**Comment by aekt** [comment]
Actually, there're two at the moment https://osv.dev/list?ecosystem=Pub&q=archive:

- https://osv.dev/vulnerability/GHSA-r285-q736-9v95
- https://osv.dev/vulnerability/GHSA-9v85-q87q-g4vg

**Comment by NicolaVerbeeck** [comment]
If you need a hand, let me know

**Comment by brendan-duncan** [comment]
Thanks. I think both those shouldn't bee too hard to fix, I'll squeeze it in while waiting for my work code to compile :-)

**Comment by NicolaVerbeeck** [comment]
![image](https://github.com/brendan-duncan/archive/assets/7778415/0ca1b325-ecd8-431e-935c-4a961eea73f2)

**Comment by brendan-duncan** [comment]
Chipping away at it. I added the symlink check. I'll get to that other vulnerability next.

**Comment by brendan-duncan** [comment]
Every time I work on this library I just want to rewrite it. I wrote it almost 10 years ago, for a personal project; lots I would do differently if I knew then what I know now. Maybe one day.

**Comment by JaredEzz** [comment]
I got a dependabot notification about this vulnerability too. Happy to wait for/help with the fix

**Comment by JaredEzz** [comment]
<img width="481" alt="image" src="https://github.com/brendan-duncan/archive/assets/13698465/6ecfc320-058a-4d0a-bbb6-5431b76cb6ff">
<img width="468" alt="image" src="https://github.com/brendan-duncan/archive/assets/13698465/5844050b-3d29-4c16-8a68-c20dfd667113">
<img width="464" alt="image" src="https://github.com/brendan-duncan/archive/assets/13698465/0a197759-5b0e-4123-bf86-985b4427955d">

**Comment by brendan-duncan** [comment]
I should have the second vulnerability patched tomorrow, and then I'll get a release out to keep the vulnerability bots from yelling at me.

**Comment by brendan-duncan** [comment]
I believe both vulnerabilities should be fixed. These only reaffirm my believe that ZIP is an awful format. Not as bad as RAR, but still awful. Sure is convenient though.

**Comment by brendan-duncan** [comment]
I'll get a version pushed as soon as I can.

**Comment by dditim** [comment]
Thanks for the fast effort put into this! 
It's highly appreciated

**Comment by 3asm** [comment]
Awesome work @brendan-duncan, much appreciated.

**Comment by kj415j45** [comment]
@jtaylor-dohle GHSA has been updated just now. GitHub takes some time to review advisory updates.
