### ISSUE TITLE
i can't unzip this file

### ISSUE THREAD

**Issue by yiiim** [brendan-duncan/archive#282]
https://huggingface.co/pcuenq/coreml-stable-diffusion/resolve/main/coreml-stable-diffusion-v1-5_original_compiled.zip

i got this exception:

ArchiveException (FormatException: Invalid Zip Signature)

**Comment by brendan-duncan** [comment]
I'm looking into it.

**Comment by brendan-duncan** [comment]
Found the issue. Fix is in 3.4.1.
