### ISSUE TITLE
I can't extract this file success, Please help me

### ISSUE THREAD

**Issue by comk** [brendan-duncan/archive#307]
[43b761a04471fcd00eee33b3b103dbe4.zip](https://github.com/brendan-duncan/archive/files/13804877/43b761a04471fcd00eee33b3b103dbe4.zip)

password : 123456

I got error "FormatException: Filter error, bad data", but I can extract successfully by local tool; 
use the extractFileToDisk method, file can be extract sucessfully, but it's content is empty (file size = 0).

tried version 3.3.1, 3.4.9

**Comment by brendan-duncan** [comment]
I pushed the fix to git. I'll get that published soon.

**Comment by brendan-duncan** [comment]
Fix is in 3.4.10

**Comment by comk** [comment]
Greatly thanks for fix and response !!!
