### ISSUE TITLE
Can't modify archive files

### ISSUE THREAD

**Issue by YancyHsu** [brendan-duncan/archive#309]
the code cant work now
_archive.files[index] = archiveFile;
maybe UnmodifiableListView block it

https://github.com/brendan-duncan/archive/blob/4c94c0a54c08cf3a0bad324e614c6d7bfe1dd835/lib/src/archive.dart#L14

**Comment by brendan-duncan** [comment]
That had to be removed because it caused the archive's cache to become invalid.

I just pushed an alternative to git, I'll publish soon:
_archive[index] = archiveFile;

**Comment by YancyHsu** [comment]
> That had to be removed because it caused the archive's cache to become invalid.
> 
> I just pushed an alternative to git, I'll publish soon: _archive[index] = archiveFile;

i modified the \archive-3.4.10\lib\src\archive.dart 

List<ArchiveFile> get files => UnmodifiableListView(_files); 

to

List<ArchiveFile> get files => _files;

instead temprorily

**Comment by brendan-duncan** [comment]
I'll have to remove the name caching if I made files a modifiable list, because if you change the list directly, the name cache (_fileMap) could become invalid.
