### ISSUE TITLE
ArchiveFile.string incorrect encodes non-ASCII data (causes dataloss)

### ISSUE THREAD

**Issue by Hixie** [brendan-duncan/archive#321]
The code currently says:

```dart
  _content = Uint8List.fromList(content.codeUnits);
```

This causes Unicode characters above U+00FE to all get turned into U+00FF and then causes the data to be encoded using ISO-8859-1, which is rather archaic.

I think that line should probably be this instead:

```dart
  _content = utf8.encode(content.codeUnits);
```

**Comment by Hixie** [comment]
Looks like the main constructor has a similar behaviour.

**Comment by urusai88** [comment]
Is this already fixed?

**Comment by brendan-duncan** [comment]
Looks like it was changed a little while ago,. I'll close this issue.
