### ISSUE TITLE
Exception thrown on encode

### ISSUE THREAD

**Issue by twoyoon** [brendan-duncan/archive#33]
Brendan,

Thanks for the archive library for Dart!

Quick question...I have a dart web app where I read text files, parse them and export the parsed text files using your archive library to make a downloadable zip file.

The library keeps crashing when I try to encode an Archive that has one ArchiveFile in it:

  Archive archive = new Archive();
//  String content = "This is test content.";
  List<int> content = [1,2,3,4,5,6,7,8,9,10];
  ArchiveFile arcfile = new ArchiveFile('test.txt', content.length*8, content);
  archive.addFile(arcfile);

  //CRASHES AT THIS POINT
  List<int> tar_data = new TarEncoder().encode(archive);
  List<int> tar_bz2 = new BZip2Encoder().encode(tar_data);
  String base64text = Convert.BASE64.encode(tar_bz2);

One question I have is for the ArchiveFile constructor, is the "size" parameter the size of the content in bytes?  or is it the size in ints?

Either way, the code crashes with this stack trace:

Uncaught Unhandled exception:
NoSuchMethodError: The method 'toRadixString' was called on null.
Receiver: null
Tried calling: toRadixString(8)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TarFile._writeInt (package:archive/src/tar/tar_file.dart:198:22)
#3      TarFile.write (package:archive/src/tar/tar_file.dart:117:5)
#4      TarEncoder.encode (package:archive/src/tar_encoder.dart:19:10)
#5      onSaveButton (http://localhost:63342/CDL2MatchboxWebVer/web/main.dart:40:41)
#6      _EventStreamSubscription._EventStreamSubscription.<anonymous closure> (dart:html:44616)

Thanks in advance for any help!

**Comment by twoyoon** [comment]
I changed some things in my code and I got it working!

Using String.codeUnits seemed to do the trick, and maybe changing to ZipEncoding?

Final Code Below:

void onSaveButton(Event e){
  Archive archive = new Archive();
  var content = "This is test content.";
  ArchiveFile arcfile = new ArchiveFile('test.txt', content.length, content.codeUnits);
  archive.addFile(arcfile);

  List<int> zip_data = new ZipEncoder().encode(archive);
  String base64text = Convert.BASE64.encode(zip_data);

//Trick to start file download in the browser
  var a = querySelector('#save');
  var mime_type = 'application/zip'; //Mime
  a.href = 'data: $mime_type ;base64,'+ base64text;
  a.click();
}

**Comment by brendan-duncan** [comment]
Great, I'm glad you found a solution!

Just for clarification, and I should really have made the code and docs more clear, if I weren't so lazy:

The **size** parameter of the ArchiveFile constructor is in bytes.

The **content** parameter can either be a `List<int>` or InputStream. `List<int>` is really sort of confusing in Dart, as it's really an interface and not an actual class, and there's no distinction between an int8, int32, etc. What it means in this case is int8, ie an array of bytes.

As you found out, in your above working code, String.codeUnits converts the string to a byte array. I suspect this may fail for non ASCII strings, if content.length doesn't equal content.codeUnits.length for characters that require more than one byte, so if you wanted to be extra safe you could do something like:
```
var bytes = new Uint8List.fromList(content.codeUnits); 
// The conversion to Uint8List may be unnecessary, I have it in my unit test code but I 
// don't remember why I didn't just use codeUnits directly. Yet another code commenting 
// fail on my part.

ArchiveFile file = new ArchiveFile('test.txt', bytes.lengthInBytes, bytes);
```
