### ISSUE TITLE
Error: Method not found: 'UnmodifiableUint8ListView'.

### ISSUE THREAD

**Issue by Trung15010802** [brendan-duncan/archive#346]
![image](https://github.com/user-attachments/assets/99d1d42c-bcf9-4efb-9721-3d66716a912c)

FLUTTER VERSION: 3.24

**Comment by brendan-duncan** [comment]
I think I removed those Unmodifiable list objects a little while ago. You're on an older version, can you update?

**Comment by Trung15010802** [comment]
> I think I removed those Unmodifiable list objects a little while ago. You're on an older version, can you update?

Some of my dependencies use archive inside. I try to use dependency_overrides but it's not working. Do you have any other way?
