### ISSUE TITLE
How to achieve asynchronous decompression？

### ISSUE THREAD

**Issue by giantss** [brendan-duncan/archive#347]
Hello author, thank you very much for providing such a great plugin.
I have a problem now. When decompressing, the loading animation I play will get stuck. I think it should be because the UI thread is blocked during decompression. How can I achieve asynchronous decompression?

**Comment by brendan-duncan** [comment]
You can try using an Isolate to do the decoding off of the main thread.

**Comment by giantss** [comment]
OK, I'll try it. Thanks for your reply.
