### ISSUE TITLE
GZip behavior in 4.0.0

### ISSUE THREAD

**Issue by alextekartik** [brendan-duncan/archive#359]
Hi and thank you for you wok on this library. I noticed some differences in Gzip encoding with the latest version (4.0.0)

* Gzip decoding fails on Chrome

Consider the following code (weird but compile with both version 3.x.y and 4.0.0 of archive)

```dart
import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:test/test.dart';

extension on List<int> {
  Uint8List asUint8List() =>
      (this is Uint8List) ? (this as Uint8List) : Uint8List.fromList(this);
}

T? _ambiguate<T>(T? value) => value;

extension on GZipEncoder {
  Uint8List doEncodeBytes(Uint8List bytes) {
    return _ambiguate(encode(bytes))!.asUint8List();
  }

  Uint8List encodeText(String text) {
    return doEncodeBytes(utf8.encode(text));
  }
}

extension on GZipDecoder {
  Uint8List doDecodeBytes(Uint8List bytes) {
    return decodeBytes(bytes).asUint8List();
  }

  String decodeText(Uint8List bytes) {
    return utf8.decode(doDecodeBytes(bytes));
  }
}

void main() {
  final encoder = GZipEncoder();
  final decoder = GZipDecoder();

  test('hello', () {
    print(encoder.encodeText('hello').sublist(8));
    // v3.y.z: [0, 255, 203, 72, 205, 201, 201, 7, 0, 134, 166, 16, 54, 5, 0, 0, 0]
    // v4.0.0: [0, 3, 203, 72, 205, 201, 201, 7, 0, 134, 166, 16, 54, 5, 0, 0, 0]
  });
  test('encode/decode', () {
    void roundTrip(String text) {
      var bytes = encoder.encodeText(text);

      var decompressed = decoder.decodeText(bytes);
      expect(decompressed, text);
    }

    // fails on v4.0.0 and chrome
    roundTrip('hello');
  });
}
```

Running on vm:
```dart
dart test -p vm
```

The tests works fine with archive 3.6.1 and 4.0.0

Running on chrome:
```dart
dart test -p chrome
```

The test works with archive 3.6.1 but fails with 4.0.0

```
00:04 +1 -1: test/archive_exp_test.dart: encode/decode [E]                                                                                                         
  Expected: 'hello'
    Actual: ''
```

* Also (maybe unrelated) encoding the same data (ignoring date in headers) is different in v3 and V4
```dart
print(encoder.encodeText('hello').sublist(8));
// v3.x.y: [0, 255, 203, 72, 205, 201, 201, 7, 0, 134, 166, 16, 54, 5, 0, 0, 0]
// v4.0.0: [0,   3, 203, 72, 205, 201, 201, 7, 0, 134, 166, 16, 54, 5, 0, 0, 0]
```

**Comment by brendan-duncan** [comment]
Thanks for letting me know, looking at it now.

**Comment by brendan-duncan** [comment]
Don't know how that slipped through. I've been sitting on this 4.0 branch for a really long time. Did lots of testing. Finally published it today because I sat on it for so long, I might never publish it otherwise.

Within a few hours you find a problem. GZip is little-endian. I accidentally changed the web gzip encoder to use big-endian. All the bytes were swapped.

I pushed the fix, and am publishing the update now.

**Comment by brendan-duncan** [comment]
Published to 4.0.1

**Comment by brendan-duncan** [comment]
I should check zlip encoder. Should have thought of that before the publish. I'll do that now.

**Comment by brendan-duncan** [comment]
Doesn't seem to be any problems with zlib.

I added tests to check the interchange of web and io versions of encoding and decoding gzip and zlib, to make sure web builds produce outputs that are the same as native builds. That should protect against this problem in the future.

**Comment by alextekartik** [comment]
Thank you for the fix. Indeed your `gzip_test.dart` is io only (it includes `dart:io`). I use a simple cross-platform test to make sure the compress data is consistent on all platforms:
```dart
test('1,2,3', () {
    var bytes = Uint8List.fromList([1, 2, 3]);
    var compressed = GZipEncoder().encodeBytes(bytes);
    // Clear date
    compressed[4] = 0;
    compressed[5] = 0;
    compressed[6] = 0;
    compressed[7] = 0;
    // and operating system
    compressed[9] = 255; // unknown operating system
    expect(compressed, [
      31,
      139,
      8,
      0,
      0,
      0,
      0,
      0,
      0,
      255,
      99,
      100,
      98,
      6,
      0,
      29,
      128,
      188,
      85,
      3,
      0,
      0,
      0
    ]);
  });
```
