### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by matanlurey** [brendan-duncan/archive#36]
It will make folks understand better what release versions do :)

**Comment by brendan-duncan** [comment]
I do have a changelog.txt, though I admit I haven't been the best about keeping it up to date. I can switch it to an MD file if that's better, and try to be better about updating it.

**Comment by matanlurey** [comment]
Oh, I didn't notice that!

One nice thing about `CHANGELOG.md` is it shows up on pub :)

Let me help out!

**Comment by brendan-duncan** [comment]
Thanks :-). I think pub used to read the txt, but it's been a while since
I've been able to do any really active dart work so I'm sure it all
changed.
