### ISSUE TITLE
Archive 4.0.1 Web Version Exception

### ISSUE THREAD

**Issue by Mike-3** [brendan-duncan/archive#365]
After upgrading to version 4.0.1 I get this error when creating the web version. There is no exception when creating the Android version.

/C:/Users/XXXX/AppData/Local/Pub/Cache/hosted/pub.dev/posix-6.0.1/lib/src/libc.dart:7:8: Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
Context: The unavailable library 'dart:ffi' is imported through these packages:

    web_entrypoint.dart => package:gc_wizard => package:archive => package:posix => dart:ffi
    web_entrypoint.dart => package:gc_wizard => package:archive => package:posix => package:ffi => dart:ffi

**Comment by Mike-3** [comment]
ffi isn't available for the web platform.

**Comment by brendan-duncan** [comment]
The posix library is only imported from extract_archive_to_disk.dart, which is only exported from archive_io.dart. These aren't usable from web apps. Are you saying it's still erroring without using any of those things?

**Comment by pezi** [comment]
Same problem - a app for all platforms. I ported the code from 3.x to 4.x

```
import 'package:archive/archive.dart';
  ....
  InputMemoryStream ifs = InputMemoryStream(zipData);
  final archive = ZipDecoder().decodeStream(ifs);
  ArchiveFile a = archive.first;
  OutputMemoryStream os = OutputMemoryStream();
  a.writeContent(os);
```

**Comment by Mike-3** [comment]
We do not use extractFileToDisk or extractArchive.
But ZipFileEncoder() and ZLibEncoder()

**Comment by brendan-duncan** [comment]
Strange. I've at least done WASM builds without issue. I'll look into it. Dart's being weird again.

**Comment by pezi** [comment]
I cleaned the cache `dart pub cache clean`, and compilation without wasm switch. Build still runs  in the same problem.

**Comment by brendan-duncan** [comment]
Thanks for letting me know. I'll get it sorted out asap.

**Comment by brendan-duncan** [comment]
I made posix a conditional import, which seems to fix the issue. Doing a bit more testing then I'll publish the fix.

**Comment by brendan-duncan** [comment]
It fixed the issue with posix, but if I import "package:archive/archive_io.dart" in a web build it still fails, because of the use of dart:io.

I have a web test, https://github.com/brendan-duncan/archive/blob/main/web/test_zip.dart. As it is, it worked before the posix change I just made. if I change archive.dart to archive_io.dart there, before it got the mentioned posix error, which went away after the change.

But it still doesn't build with archive_io.dart, because of the use of dart:io in those exported files.

So I'm still a bit confused how you got the posix error without using archive_io.dart.

**Comment by brendan-duncan** [comment]
If you could test the git version before I publish, that would help. I'll come back to this later, have to go do my day job now.

**Comment by pezi** [comment]
Changing to archive.dart fixes the problem - but I was foreced to exclude the code which creates the ZIP flutter asset file with ZipFileEncoder(). But this code not needed for the app.

**Comment by brendan-duncan** [comment]
I'll see what I can do about it. I believe ZipFileEncoder didn't need dart:io previously.

**Comment by pezi** [comment]
Thanks for your great work!

**Comment by Mike-3** [comment]
Thank you very much
