### ISSUE TITLE
Failed to precompile archive:tar after upgrade SDK to 1.24 

### ISSUE THREAD

**Issue by Zhihar** [brendan-duncan/archive#39]
With the upgrade of Dart SDK to 1.24 I get an error:

`Failed to precompile archive:tar:
'package:convert/src/hex/decoder.dart': malformed type: line 21 pos 13: cannot resolve class 'ChunkedConverter' from 'HexDecoder'
    extends ChunkedConverter<String, List<int>, String, List<int>> {
            ^`

This causes me to keep 1.23 for now.

**Comment by brendan-duncan** [comment]
I'm trying to figure out what this error is, it's not obvious it's archive specific but maybe some pubspec package version needs to be updated. I'll investigate.

**Comment by brendan-duncan** [comment]
I update the dependency requirement on crypto to >=2.0.0, as this is the only place of indirect dependency to convert. This update has been put into the 1.0.31 version update I just published.  If you still have this error, you might want to try running `pub repair`. Not sure what else there is, hope this works for you.

**Comment by Zhihar** [comment]
I'll try and report, thanks!

**Comment by Zhihar** [comment]
OK, looks like it solved the issue. Thanks!
