### ISSUE TITLE
bzip2_encoder does not work in release build

### ISSUE THREAD

**Issue by stephan-gruen** [brendan-duncan/archive#40]
Because of the [bad behaviour I reported here](https://github.com/dart-lang/sdk/issues/30841) the code

https://github.com/brendan-duncan/archive/blob/b6ddae37d779271e12d9f26df28ad1dda7590e7a/lib/src/bzip2_encoder.dart#L1312

causes problems if bbSize = 0! (What will happen in every call)

Always make sure not to shift in negativ numbers. Here is my temp fix I put in. But of course this will only be in there until the next update.
 ```
     if (i < 255) {
        int bbStart = _ftab[ss << 8] & CLEARMASK;
        int bbSize = (_ftab[(ss + 1) << 8] & CLEARMASK) - bbStart;
        int shifts = 0;

        if (bbSize > 0) {
        
          while ((bbSize >> shifts) > 65534) {
            shifts++;
          }

          for (j = bbSize - 1; j >= 0; j--) {
            int a2update = ptr[bbStart + j];
            int qVal = (j >> shifts) & 0xffff;
            quadrant[a2update] = qVal;
            if (a2update < BZ_N_OVERSHOOT) {
              quadrant[a2update + nblock] = qVal;
            }
          }
          _assert(((bbSize - 1) >> shifts) <= 65535);
        }
```
As @rakudrama pointed out you can also force the sign back:
`_assert(((bbSize - 1) >> shifts).toSigned(32) <= 65535);`

**Comment by stephan-gruen** [comment]
**Please, please, after 8 (!!) months someone fix this bug. It would be much appreciated!**

- Because this is a very serious bug. 
- It causes loss of data, because it cuts off the encoded data.
- It will only take effect in production code. 
- It is not noticeable in development or even testing.
- The fix is only one simple line of code and a reformat!

I try to explain again what the problem is: 
The "error" is in this code segment:
https://github.com/brendan-duncan/archive/blob/b6ddae37d779271e12d9f26df28ad1dda7590e7a/lib/src/bzip2_encoder.dart#L1296-L1314

First:
_assert is not part of the for loop. It's sitting under the for-loop. 

Second:
In development:
At on point bbSize will be 0. shifts is 0. 
If you call _assert with bbSize=0 you will shift a negative number. In development (-1 >> 0) is 0. 0 <=65535. That is a true statement, so the loop continues.

But in production code (or build code or release code, you name it) this behaviour is no longer true:
(-1 >> 0) is now interpreted as maxInt, not 0! MaxInt is not <= 65535, so _assert stops the loop, because it thinks the algorithm is done or something is wrong. The rest of the data is simply not processed! This is a major bug!


How to fix it:
Do not call _assert if bbSize==0.
If you look at the code you see that there is no need anyway to process the while and the for loop if bbSize==0. 

So a simple 
```
if (bbSize > 0) {
```
will do the job. As a bonus put brackets around 'quadrant[a2update + nblock] = qVal;'

```
     if (i < 255) {
        int bbStart = _ftab[ss << 8] & CLEARMASK;
        int bbSize = (_ftab[(ss + 1) << 8] & CLEARMASK) - bbStart;
        int shifts = 0;

        if (bbSize > 0) {

          while ((bbSize >> shifts) > 65534) {
            shifts++;
          }

          for (j = bbSize - 1; j >= 0; j--) {
            int a2update = ptr[bbStart + j];
            int qVal = (j >> shifts) & 0xffff;
            quadrant[a2update] = qVal;
            if (a2update < BZ_N_OVERSHOOT) {
              quadrant[a2update + nblock] = qVal;
	    }
          }
          _assert(((bbSize - 1) >> shifts) <= 65535);  

        }
     }
```

**Comment by brendan-duncan** [comment]
Sure, I’ll look into it this evening.

**Comment by brendan-duncan** [comment]
Really sorry this fell off the radar, work (which doesn't include dart anymore) and kids have been keeping me from paying as much attention as I should to these projects. I had to deal with those negative shift issues a lot with the image library, I'm not surprised this one got through, and I'm sure there are others. I pushed your good suggestion, and I'll try and be more attentive.

**Comment by stephan-gruen** [comment]
I'm just happy you wrote this awesome package!
Kids and family first!
