### ISSUE TITLE
1.0.31 is generating broken tar archives

### ISSUE THREAD

**Issue by nex3** [brendan-duncan/archive#41]
The latest version seems to be generating archives that can't be decompressed with standard `tar` implementations. To reproduce:

```dart
import 'dart:io';

import 'package:archive/archive.dart';

void main() {
  new File("out.tar.gz").writeAsBytesSync(
      new GZipEncoder().encode(new TarEncoder().encode(new Archive())));
}
```

Running `tar xzf out.tar.gz` with GNU tar 1.27.1 prints:

```
gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The same script produces a valid tar file with `archive` 1.0.29.

**Comment by brendan-duncan** [comment]
Looks like GZipEncoder is writing the compressed data twice :-/.   Fix coming.

**Comment by brendan-duncan** [comment]
published fix as 1.0.32.

**Comment by nex3** [comment]
Are there plans to add tests that verify the generated archives against standard archive implementations? As it stands, I'm nervous about relying on this package for real-world archive generation if a stray bug could break our distribution again.

**Comment by brendan-duncan** [comment]
Enabling crc validation in the current tests would have caught it. I'll do
that.

**Comment by brendan-duncan** [comment]
The unit test updates to make sure they do crc verification have been pushed, and I verified that the previous bug would have been caught by doing that. 

As far as using the package for real-world archive generation, that's up to you. I do the best that I can with the time that I have, but in reality that's a tiny amount of time and likely to be even less in the near future. At the current rate the libraries I put here on github require little enough attention that it's not too big a deal to fix the occasional problem, but I really can't contribute any more, so I'm going to have to turn down any future feature requests like the file streaming that was wanted for the pub system.
