### ISSUE TITLE
Can't reencode decoded archive

### ISSUE THREAD

**Issue by sestegra** [brendan-duncan/archive#42]
Scenario
- Create OpenDocument with LibreOffice for instance.
- Launch ```dart archive.dart default.ods``` (see code below)

Get 'default.ods' file from following link:
https://github.com/sestegra/spreadsheet_decoder/raw/master/test/files/default.ods

archive.dart
```
import 'dart:io';
import 'package:archive/archive.dart';

void main(List<String> args) {
  var input = args[0];

  var archive = new ZipDecoder().decodeBytes(new File(input).readAsBytesSync(), verify: true);
  var zip = new ZipEncoder().encode(archive);
  archive = new ZipDecoder().decodeBytes(zip, verify: true);
}
```

```
$ dart archive.dart default.ods
Unhandled exception:
ArchiveException: Invalid CRC for file in archive.
#0      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:29:11)
#1      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:10:12)
#2      main (file:///Users/sestegra/reyer/repos/spreadsheet_decoder/example/archive.dart:64:30)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by sestegra** [comment]
The issue is coming from ```file.content```.
If I add cloneArchive in between, it works better

```
Archive cloneArchive(Archive archive) {
  var clone = new Archive();
  archive.files.forEach((file) {
    if (file.isFile) {
      var content = (file.content as Uint8List).toList();
      var copy = new ArchiveFile(file.name, content.length, content);
      clone.addFile(copy);
    }
  });
  return clone;
}
```

**Comment by brendan-duncan** [comment]
I'm really sorry I've neglected this issue. I'll make sure to get on it now.

**Comment by brendan-duncan** [comment]
I pulled out your fix from your PR and pushed that, to avoid some conflicts. I'll take a look at your version of the zip_tests, which look good but I haven't had a chance to get to it yet. Again, sorry this is like 8 months late, kids and work (which no longer includes dart) have kept me from these projects. I verified your ods test works.
