### ISSUE TITLE
Provide example for how to write directories ?

### ISSUE THREAD

**Issue by Rockvole** [brendan-duncan/archive#49]
In your example it looks like you recursively write the files found in the archive.
In the root of my archive is a directory and I get the error :

    E/flutter ( 3054): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    E/flutter ( 3054): FileSystemException: Cannot create file, path = '/data/data/com.rockvole.kbmlviewer/app_flutter/out/how2instructions-master/' (OS Error: Is a directory, errno = 21)
    E/flutter ( 3054): #0      _File.throwIfError (dart:io/file_impl.dart:628)
    E/flutter ( 3054): #1      _File.createSync (dart:io/file_impl.dart:271)
    E/flutter ( 3054): #2      _PreferencesPageState._decompressFile (/data/data/com.rockvole.kbmlviewer/cache/kbml_viewerQGEUIX/kbml_viewer/lib/preferences.dart:56:11)
    E/flutter ( 3054): #3      _PreferencesPageState.getPreferenceText.<anonymous closure>.<anonymous closure> (/data/data/com.rockvole.kbmlviewer/cache/kbml_viewerQGEUIX/kbml_viewer/lib/preferences.dart:124:19)
    E/flutter ( 3054): #4      _RootZone.runUnary (dart:async/zone.dart:1381)
    E/flutter ( 3054): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129)
    E/flutter ( 3054): #6      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
    E/flutter ( 3054): #7      _Future._propagateToListeners (dart:async/future_impl.dart:662)
    E/flutter ( 3054): #8      _Future._complete (dart:async/future_impl.dart:467)
    E/flutter ( 3054): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51)
    E/flutter ( 3054): #10     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:255)
    E/flutter ( 3054): #11     _PreferencesPageState._downloadFile (/data/data/com.rockvole.kbmlviewer/cache/kbml_viewerQGEUIX/kbml_viewer/lib/preferences.dart:45:5)
    E/flutter ( 3054): #12     _RootZone.runUnary (dart:async/zone.dart:1381)
    E/flutter ( 3054): #13     _FutureListener.handleValue (dart:async/future_impl.dart:129)
    E/flutter ( 3054): #14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
    E/flutter ( 3054): #15     _Future._propagateToListeners (dart:async/future_impl.dart:662)
    E/flutter ( 3054): #16     _Future._complete (dart:async/future_impl.dart:467)
    E/flutter ( 3054): #17     _SyncCompleter.complete (dart:async/future_impl.dart:51)
    E/flutter ( 3054): #18     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:255)
    E/flutter ( 3054): #19     getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:44:3)
    E/flutter ( 3054): #20     _RootZone.runUnary (dart:async/zone.dart:1381)
    E/flutter ( 3054): #21     _FutureListener.handleValue (dart:async/future_impl.dart:129)
    E/flutter ( 3054): #22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
    E/flutter ( 3054): #23     _Future._propagateToListeners (dart:async/future_impl.dart:662)
    E/flutter ( 3054): #24     _Future._complete (dart:async/future_impl.dart:467)
    E/flutter ( 3054): #25     _SyncCompleter.complete (dart:async/future_impl.dart:51)
    E/flutter ( 3054): #26     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:255)
    E/flutter ( 3054): #27     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:5)
    E/flutter ( 3054): #28     _RootZone.runUnary (dart:async/zone.dart:1381)
    E/flutter ( 3054): #29     _FutureListener.handleValue (dart:async/future_impl.dart:129)
    E/flutter ( 3054): #30     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
    E/flutter ( 3054): #31     _Future._propagateToListeners (dart:async/future_impl.dart:662)
    E/flutter ( 3054): #32     _Future._completeWithValue (dart:async/future_impl.dart:477)
    E/flutter ( 3054): #33     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
    E/flutter ( 3054): #34     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    E/flutter ( 3054): #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

**Comment by Rockvole** [comment]
An example would be :

    _decompressFile(File file) {
      List<int> bytes = file.readAsBytesSync();
      Archive archive = new ZipDecoder().decodeBytes(bytes);
      for (ArchiveFile file in archive) {
        String filename = file.name;
        List<int> data = file.content;
        if (file.isFile) {
          new File('$_rootDir/out/' + filename)
            ..createSync(recursive: true)
            ..writeAsBytesSync(data);
        } else {
          new Directory('$_rootDir/out/' + filename)
              .create(recursive: true);
        }
      }
    }

**Comment by brendan-duncan** [comment]
Thanks for the suggestion, I'll fix up the example shortly.
