### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [brendan-duncan/archive#50]
Running tests in dart 2 mode

```
dart --preview-dart-2 test/input_stream_test.dart
```

  type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast where
    List is from dart:core
    List is from dart:core
    int is from dart:core
  
  dart:core                                                                         Object._as
  ../../archive/lib/src/util/input_stream.dart 18:14  new InputStream
  ../..//archive/test/input_stream_test.dart 6:29      main.<fn>

**Comment by brendan-duncan** [comment]
Finally got around to this, sorry it took so long. Should be good now.
