### ISSUE TITLE
File names with uncommon chararacters do not always get correctly decoded

### ISSUE THREAD

**Issue by ShadowJonathan** [brendan-duncan/archive#56]
orthros/dart-epub#31

Seems like the `Archive` class cannot properly handle encoded characters in file headers.

(please note that this has been tried with `archive~1.0.33`, please close issue when already fixed)

**Comment by orthros** [comment]
I can reproduce this error in `archive 2.0.2`

**Comment by brendan-duncan** [comment]
I pushed archive 2.0.3 that should fix this problem by reading filenames as utf8.

**Comment by ShadowJonathan** [comment]
Did you test it on the epub/zip archive in question?

**Comment by ShadowJonathan** [comment]
Alright, seems like we're done here then
