### ISSUE TITLE
Can this package be changed to fall-back to builtin Zlib decoder when available?

### ISSUE THREAD

**Issue by mraleph** [brendan-duncan/archive#62]
According to the issue https://github.com/dart-lang/sdk/issues/35352 users might fall into performance trap when using this package instead of builtin ZLibCodec on Dart VM. 

Can we change this package in a way that it falls back to faster builtin implementation when dart:io library is available?

**Comment by brendan-duncan** [comment]
Since Dart doesn’t have platform based conditional compilation, I’ll need to make an interface class and implement it with both io and non io solutions, and the solution used would be determined by whether you import archive or archive_io. That’s a bit ugly, but I think doable.

**Comment by natebosch** [comment]
Note that there are platform specific imports. For example you can use either the IO or web http code path with one import:

https://github.com/dart-lang/http/blob/ffe786a872c0d443cc4fa6baa923d69059b66399/lib/src/client.dart#L11-L16

In this case you likely won't need a "stub" file, you can implement the default import fully with Dart code, and when `dart:io` is available import a different implementation that uses `ZLibCodec`.

**Comment by brendan-duncan** [comment]
Well look at that! I haven't been following Dart as closely as I used to, glad that got a solution. I'll look into putting it together hopefully soon.

**Comment by brendan-duncan** [comment]
I committed a version that uses ZLibCodec under the hood when dart:io is used.
https://github.com/brendan-duncan/archive/commit/547e94df471ac91fa51f5f9905d8a7422367ca5f
I still need to test that I didn't break the javascript build version before I publish it.

**Comment by brendan-duncan** [comment]
javascript version still seems to be ok, so I went ahead and published the update as 2.0.5
