### ISSUE TITLE
Provide support to add directory structure.

### ISSUE THREAD

**Issue by jasxir** [brendan-duncan/archive#63]
`ZipFileEncoder.addDirectory` only adds files within the directory and ignores the sub-directories. Need support to be able to archive full directory structure. please provide an example if this is possible.

Thanks in advance :smiley:

**Comment by brendan-duncan** [comment]
ZipFileEncoder.addDirectory should already be including files from all sub-directories. Are you finding that not to be the case? It uses `List files = dir.listSync(recursive: true);` to gather the list of files from the directory, which recursively lists sub-directories.

**Comment by jasxir** [comment]
Apologies I'm using `ZipFileEncoder.zipDirectory` which it self uses `addDirectory` but when I check the archive, it only has the files in the root of the given source directory, no sub-directories and no files contained within the sub-directories.

**Comment by jasxir** [comment]
I used `directory.listSync(recursive: true)` to list the files and it's listing everything fine.

**Comment by jasxir** [comment]
My bad, the directory structure wasn't present when the archive was created, operations were happening in parallel.
