### ISSUE TITLE
Throw a useful error for invalid archives

### ISSUE THREAD

**Issue by nex3** [brendan-duncan/archive#77]
Right now, if a decoder is passed invalid bytes, it throws a subclass of `Error`. For example, the following example throws a `RangeError`:

```dart
import 'package:archive/archive.dart';

void main() {
  TarDecoder().decodeBytes([1, 2, 3]);
}
```

The `Error` superclass is supposed to represent programmer error, not data error. A failed decode should throw a `FormatException` or, better yet, an archive-specific subclass of `FormatException` that can be used to distinguish archive exceptions from other exceptions.

**Comment by brendan-duncan** [comment]
That thrown error was an array bounds exception. I added a check for that type of invalid archive and have it throw an ArchiveException.

**Comment by brendan-duncan** [comment]
This is been pushed into version 2.0.10.
