### ISSUE TITLE
What is the generator polynomial for the CRC32 implementation here?

### ISSUE THREAD

**Issue by thosakwe** [brendan-duncan/archive#82]
Hello, Mr. Duncan! Quick question - what's the generator polynomial being used for the table in the `Crc32` class in this package?

I'm assuming it is `0x04c11db7` (and I see it in the `_CRC_TABLE` too), but I figured it couldn't hurt to ask.

Thanks.

**Comment by brendan-duncan** [comment]
Yes, but with the least-significant-bit first order (0xedb88320). I'll be the first to admit I'm not an expert in this area by any means and had to look up what a generator polynomial was before I figured out what you were asking. Here's the code:
```
  var _CRC32_TABLE = List<int>(256);
  for (int i = 0; i < 256; i++) {
    int temp = i;
    for (int j = 0; j < 8; j++) {
        if (temp & 1 != 0) {
            temp >>= 1;
            temp ^= 0xedb88320;
        } else {
            temp >>= 1;
        }
    }
    _CRC32_TABLE[i] = temp;
  }
```

**Comment by thosakwe** [comment]
Thank you!!! Appreciate it.
