### ISSUE TITLE
decompress a zip with a single file inside

### ISSUE THREAD

**Issue by blondie63** [brendan-duncan/archive#91]
Hi, looking sample i see only case with archive with many files inside
How can i expand a zip with a single file inside ?
Thanks for an example

**Comment by brendan-duncan** [comment]
A zip with a single file inside it is no different than a zip with multiple files. The file count will just be one.

**Comment by blondie63** [comment]
Yes i know but I was just asking for a leaner code.. :)

**Comment by brendan-duncan** [comment]
GZip or BZip2 compression might be better for single files; zip and tar are archive formats. If I added special purpose code for single file zips, it would be adding bloat for a very specific purpose and trying to avoid library bloat is a constant challenge. Sorry :-/

**Comment by blondie63** [comment]
ok, NP :)
