### ISSUE TITLE
Add xz Support

### ISSUE THREAD

**Issue by Nexushunter** [brendan-duncan/archive#94]
Hi, I noticed when using this package with a tar file that has been compressed into a lossless compress format, specifically `tar.xz`, the package fails to properly decompress the application. I am willing to assist but unsure of where to start. 

Dart Version: 2.7.0
Archive Version: 2.0.13

Thanks :smile:

**Comment by brendan-duncan** [comment]
I don't have XZ compression support currently, only GZip and BZip2. If you wanted to add XZ support, help is always greatly appreciated. If you did want to work on it, please don't port/derive from any GPL code. Most of the standard XZ code is in public domain, so porting that should be fine, https://git.tukaani.org/?p=xz.git;a=tree;h=refs/heads/master;hb=refs/heads/master. There are some other ports of it, too. If you do port something, please add necessary attributions to the LICENSE file.  GZipDecoder could be used as a reference; you'd want to similarly add XZDecoder (and possibly XZEncoder, if you're up to it). If you're understandably not up to doing it (it's not trivial), I could get to it but the time I have to work on it is really variable so it might take quite a while, or I might get to it quickly, finding time to work on my own projects is hard but sometimes it's lucky.

**Comment by NexisHunter** [comment]
Thanks for the rapid reply, I will try to set up the decoder but the encoder may have to come at a later date due to time constraints, I'm a University student and work full time.

**Comment by SwissCheese5** [comment]
Any updates?

**Comment by NexisHunter** [comment]
@SwissCheese5 I plan on starting it next week.
